<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo "White Rabbit" ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/jquery-1.9.1.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/jquery.bxslider.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/jquery.simplePagination.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/jquery-ui.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/modernizr-2.6.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/vendor/opacity-rollover2.1.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/common.js') ?>"></script>
<!--[if lt IE 7]>
<script type="text/javascript">
    //<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
